### ISSUE TITLE
[bug] search feature disabling when search tracking is on. 

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/inbound-pro#151]
Not a global bug, but I'm getting steady reports. Will have to run an investigation.

**Comment by MattBissett** [comment]
I think this is caused by search form that aren't constructed with a "search" type input.

At init, the Inbound Analytics tags all the forms that it thinks are search forms with a "submit" event listener.
The event listener is tied to a series of functions that:

1. Stops the form submission
2. Saves search data to local storage/browser cookie
3. Resumes the form action after the data is saved

I think where the hiccup is at step 2. The function that collects the data looks for an input of the type "search". And when it finds the input, it extracts the search and sends it off to be saved in the browser by another function.

I think what's happening is a "search" type input is not being found, so an empty check is failing because the search string is empty, then execution stops and the form doesn't get released.

It should be this line: https://github.com/inboundnow/inbound-pro/blob/master/core/shared/assets/js/frontend/analytics-src/analytics.forms.js#L754

Probably what needs to be added is a _inbound.Forms.releaseFormSubmit(form); call right before the return statement.

**Comment by MattBissett** [comment]
I'm not certain it will work, but it might be a good idea to redo the for loop at https://github.com/inboundnow/inbound-pro/blob/master/core/shared/assets/js/frontend/analytics-src/analytics.forms.js#L736 to this:

`            var searchQuery = [];
            for (var input in inputsObject) {
                var inputValue = inputsObject[input]['value'];
                var inputType = inputsObject[input]['type'];
                var placeHolder = inputsObject[input]['placeholder']

                /* Add custom hook here to look for additional values */
                if (typeof(inputValue) != "undefined" && inputValue != null && inputValue != "") {
                    // This is for mapping all fields of a search form. The resulting string is processed 
                    // in inbound-pro\classes\admin\report-templates\report.lead-searches-and-comments.php
                    // In the function print_action_popup()
                    // searchQuery.push(input + '|value|' + inputsObject[input]['value'].join(','));
                    
                    // get the search input value
                    if(inputType == 'search'){
                        searchQuery.push('search_text' + '|value|' + inputsObject[input]['value']);
                    }elseif(placeHolder.indexOf('search') !== -1){
                       searchQuery.push('search_text' + '|value|' + inputsObject[input]['value']);
                    }
                }
            }`

What this _should_ do is first check to see if there's a "search" type input. If there isn't, it looks to see if there's an input that has the placeholder of "search". If the input does, it pushes that value.

**Comment by atwellpub** [comment]
Thank you Matt. I'm not sure I want to do the ladder because it unfairly targets the English language as a backup and doesn't target other languages. We could target the name attribute possibly? Usually this is english centric. 

I'll run the tests with the modified release + return. Avada is a theme with the issue correct?

**Comment by MattBissett** [comment]
I've seen it on the "The7" theme as well Avada, but they both have the same search from setup.

Also in both themes, the input's name is "s", that seems a bit vague but maybe it's a standard name.

**Comment by MattBissett** [comment]
I guess what input other than a search one would have just "s" as a name?

**Comment by atwellpub** [comment]
That's correct most s names imply search in WP. Thanks for the code pointers. Will get a handler added in here in a little while.

**Comment by atwellpub** [comment]
Hi Matt I think I have it working with Avada. Will you send me The7 theme for testing?

**Comment by MattBissett** [comment]
Unfortunately I don't have the The7 theme, I looked at someone's site who was having the issue and he was running The7 there.

**Comment by MattBissett** [comment]
What do you think about releasing the form on this line if there isn't query?

https://github.com/inboundnow/inbound-pro/blob/38cb14fea2faa51121db8fe551f690202ef82963/core/shared/assets/js/frontend/analytics-src/analytics.forms.js#L758

**Comment by atwellpub** [comment]
I think it's a good idea I'll get it added in.
