### ISSUE TITLE
{{Featured image}} CTA doesn't work in article page

### ISSUE THREAD

**Issue by kevin-colleter** [inboundnow/inbound-pro#176]
previously : https://github.com/inboundnow/inbound-pro/issues/173

Hello @atwellpub !

It seems that in an article page, the CTA thumbnail is replaced by the article thumbnail.
behind {{featured_image}} => get_the_post_thumbnail_url() take the context in our case the feature_image of the article.

How can we access to the {{featured_image}} of the CTA, when it's insert in an article page ?
Thank you ! :-)

**Comment by atwellpub** [comment]
Hi Kevin I don't think you can. We designed Calls to Action plugin to not depend on the featured image setting and instead use image upload settings provided by the CTA template itself. http://docs.inboundnow.com/guide/how-to-create-custom-call-to-action-templates/

When I added the {{featured-image}} token it was intended to use the featured image of the article instead of a CTA featured image. 

Cheers for the interest! Happy to chat it over.

**Comment by kevin-colleter** [comment]
Hi Atwellpub,

I understood but users could be confused when they are uploading a featured_image in this field. Is it possible to change the behavior, and permit to display the "featured_image" uploaded in the CTA back office ? Thank you

**Comment by atwellpub** [comment]
Oh that's a mistake on my part. The featured image input should not be available when editing a call to action. I'm going to remove support for it. I can't imagine any situation where it's being leveraged and if there then it's possible to restore support programatically.
