### ISSUE TITLE
[class.cta.render] $is_preview

### ISSUE THREAD

**Issue by kevin-colleter** [inboundnow/inbound-pro#178]
Hello,

In some articles pages my CTAs are not displayed.
The "display" attribute is set on "none".
So I have few questions about the variable **$is_preview** in the file **class.cta.render.php**.
May you explain me the goal of this variable ?

I don't understand this part precisely (in every case the result is "none") : (line 1126-1127)
**/* Reveal Variation if Preview */
(self::$instance->is_preview) ? $display = '**none**' : $display = '**none**';**

Why the variable $display is never set before ?

Sometimes it works sometimes no, I need help :) 

Thank you !

**Comment by atwellpub** [comment]
It looks like self::$is_preview is set as a variable if the CTA is being previewed from within the admin, but right here at this line it's not relevant. It looks like it was relevant at one time but was disabled by setting both options to display none:
https://github.com/inboundnow/inbound-pro/blob/master/core/cta/classes/class.cta.render.php#L1127

Here's where we setup a preview:
https://github.com/inboundnow/inbound-pro/blob/master/core/cta/classes/class.cta.render.php#L1414-L1486

If the front end render is sometimes failing it could be because the frontend ajax call to determine the CTA variation is timing out or failing and then the load call never arrives. Could happen on high traffic sites or shared servers. 

WordPress isn't friendly on frontend AJAX calls. And they have to be ajax to skip the cache or we'd have to outsource the counter system to a 3rd party.

**Comment by cedrox** [comment]
Hello, 
We tried to change your code to 
  /* Reveal Variation if Preview */
            (self::$instance->is_preview) ? $display = 'block' : $display = 'block';

And it work back again. I think this is not from ajax. There is a true problem with this line...

Thanks for your feedback. Always interesting :)

**Comment by atwellpub** [comment]
Could you link me to a page that's having inappropriate behavior? 

If you change that to ? block : block; it most likely will show every variation instead of just one. I believe.

**Comment by kevin-colleter** [comment]
The link is https://experiences.microsoft.fr/business/confiance-numerique-business/cloud-question-de-confiance/

If you change the CSS of CTAs : display : **block** by **none**. It will be exactly like originally.

Can you explain me this behavior ?
thank you ! :-)

**Comment by kevin-colleter** [comment]
Hey Atwellpub,

We are not using variations generally.
This is a print screen of our CTA :
![cta_settings](https://user-images.githubusercontent.com/7511437/33555203-c4f299d8-d8ff-11e7-86be-0fcaac50cd63.PNG)

I will send you the url of the page with the inappropriate behavior.

Thank you ! :-)

**Comment by atwellpub** [comment]
Looking at the example page you've a JS error. JS errors will prevent the reveal scripts for your CTA. https://www.screencast.com/t/OTJaXjmVgld

Tank the JS error and the CTA behavior should correct.
