### ISSUE TITLE
Request admin-ajax.php

### ISSUE THREAD

**Issue by kevin-colleter** [inboundnow/inbound-pro#180]
Hello,

I have a question about the request : **admin-ajax.php**
As you can see below the **TTFB** is very bad because of this request :
![github2](https://user-images.githubusercontent.com/7511437/33888765-4bd31104-df4e-11e7-8b6f-e08f288dfcd9.PNG)

There is a lot of CTA impressions : 
![github](https://user-images.githubusercontent.com/7511437/33888567-ba48ea10-df4d-11e7-9c29-989fdadf906b.PNG)

One solution was to comment the content of **wp_cta_record_impressions**, but do you have a better solution to reduce the **TTFB** ? Can we avoid this part if we don't have any variations ?

**Comment by atwellpub** [comment]
I believe you've uncovered a bug. I didn't notice it because it's only active when Calls to Action is run by itself.  It's not an issue when Inbound Pro is loading Calls to Action because the tracking system differs a little bit. 

I'll just tagged commit that should fix it. I also just pushed the changes to WordPress.org. Will you check and confirm?

**Comment by atwellpub** [comment]
There's also a setting in wp-admin->CTA->Settings that will kill variation loading and default all CTAs to variation A. But it can't stop using AJAX for recording CTA impressions.

**Comment by kevin-colleter** [comment]
Hey Atwellpub, 
The release 3.3.6 will resolve this bug ?
The new content (3.3.6) is already available on github ?

**Comment by atwellpub** [comment]
Heya yes it should. Here's the commit:
https://github.com/inboundnow/inbound-pro/commit/6a041d406bf1801da11965ca7e9e080e3878c3ba
