### ISSUE TITLE
Images Not Working in Emails with ShortPixel Adaptive Images

### ISSUE THREAD

**Issue by travispflanz** [inboundnow/inbound-pro#186]
No images are coming through in emails - including the "Logo URL" image.

I am using the simple responsive template and none of the images are coming through in emails OR when previewing.

Email sent to Gmail account - https://i.imgur.com/E9Q7RpL.png

Email preview page - https://i.imgur.com/EUu0V02.png

**Comment by atwellpub** [comment]
@travispflanz Hey Travis! 

I'm running tests with my local install, Simple Responsive template, and the preview component and the images are showing up. 

What happens when you view the HTML source of the image of the preview page? You also may be able to share the mail preview link here for eval. I think previews are public.

**Comment by travispflanz** [comment]
Here is the email preview - https://www.searchcentered.com/mail/51222/?inbvid=0

I found the cause of the error. 

It appears there is some sort of a conflict with ShortPixel Adaptive Images - https://wordpress.org/plugins/shortpixel-adaptive-images/

When deactivated (it is currently active), all images display as expected, both in the preview and in the email that is sent.

I did come across this thread, however - https://wordpress.org/support/topic/all-images-src-are-replaced-with-dataimage-base-64/

Is it possible that the Emails function of Inbound Now deactivates JQuery? On the preview page, the image is replaced with base64 code - https://i.imgur.com/ZgdxqG8.png

I will reach out to ShortPixel to have them check out this thread, as well.

**Comment by atwellpub** [comment]
The fields are still powered by ACF so they could be being filtered/modified by a 3rd party plugin like ShortPixel Adaptive Images. 

Because the email templates are prepped for email clients we're not loading in any enqueued JS assets (wp_head/wp_footer) so jQuery will not be available as well as third party enqueued scripts.  

Maybe somehow the SPAI plugin can ignore modifying the ACF fields when the custom post type is `inbound-email`

**Comment by travispflanz** [comment]
Here's my public thread with them - https://wordpress.org/support/topic/all-images-src-are-replaced-with-dataimage-base-64-on-inbound-now-pro/

I hadn't relayed your last message yet, but this is what they said - https://i.imgur.com/KEVu08B.png

Adding a URL parameter to the preview page still doesn't do anything for the actual email that is delivered however... I'm hoping they will come post something here. 😀

**Comment by travispflanz** [comment]
ShortPixel has fixed this issue with the newest version (1.2.5) of the ShortPixel Adaptive Images plugin and everything seems to be working as expected now.
