### ISSUE TITLE
Outbound links issue

### ISSUE THREAD

**Issue by mcpacific** [inboundnow/inbound-pro#199]
I have v. 1.9.9.7.6 installed on Wordpress. It seems that all my outbound links are being rewritten to /inbound/generated_code.

1. How is the enabled or disabled
2. If I keep it enabled, where do I see the reports for the clicks?

I can't find any documentation on this.

**Comment by atwellpub** [comment]
Hi there, 

I believe by design they should only track inside landing pages and call-to-action blocks. But not everywhere else. 

I just dug up what seems to be our documentation on it:
https://docs.inboundnow.com/guide/tracking-conversions-posts-pages/

Looks like any link that has the class `inbound-track-link` will automatically convert the URL to a tracked link. Does your site have these class names added to links?
